# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np
print(np.version)
print(np.show_config())

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    li

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [7]:
nums_list = list(range(10))
nums_arr = np.array(nums_list)
nums_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [10]:
arrd9 = np.zeros((2, 2, 2, 2, 2, 2, 2, 2, 2))
arrd9

array([[[[[[[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]],



           [[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]]],




          [[[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]],



           [[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]]]]],





         [[[[[[0., 0.],
              [0., 0.]],

             [[0., 0.],
              [0., 0.]]],


            [[[0., 0.],
              [0., 0.]],

             [[0.,

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [13]:
arr_for_mb = np.arange(27).reshape(3, 3, 3)
arr_for_mb.itemsize * arr_for_mb.size

216

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
import numpy as np
arr12 = np.zeros((7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7))
arr12[0][0, 5] = 1
arr12[0]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [3]:
arr7 = np.arange(20, 60)
arr7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [9]:
print(arr7[::-1])

[59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36
 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
arr9 = np.arange(12, 21).reshape(3, 3)
arr9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
arr10_1 = np.array([3, 7, 0, 0, 9, 0])
arr10_2 = np.array([0, 1, 2, 3, 4, 5])

bools = arr10_1 != 0
print(arr10_2[bools])

[0 1 4]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [13]:
arr11 = np.random.randint(20, size=(2, 2, 2))
arr11

array([[[ 4, 15],
        [10, 16]],

       [[ 6,  9],
        [18, 10]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [16]:
arr12 = np.random.randn(9, 9)
print(arr12.min())
print(arr12.max())

-2.131282101587395
3.4393567511920637


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [25]:
# 0
# True
# True
# 0
# True
# False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [22]:
arr14_1 = np.random.randint(18, size=(6, 3))
arr14_2 = np.random.randint(12, size=(3, 4))

np.dot(arr14_1, arr14_2)

array([[254,  85, 247, 245],
       [346, 129, 169, 219],
       [239, 132, 182, 159],
       [193,  76,  99, 122],
       [ 89,  41,  75,  70],
       [237, 124,  62,  89]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
#Birinchisi 9 chiqaradi chunki -1 niyam 0 dan 5 (kirmaydi) gacha bo'lgan sonlar qatoridagi bitta array elementi deb hisoblaydi, natijada sum([0, 1, 2, 3, 4, -1]) bo'ladi
#Ikkichisida numpy kutubhonasi chaqirilgandan keyin endi sum methodi numpyga tegishli boladi va uning ishlashi oddiy pythonning sum functionidan farq qiladi, yani berilga 2 chi element,
                                                                                #qaysi axis uchun bajarilishi korsatadi, natijadi sum([0, 1, 2, 3, 4]) ya'ni 10 boladi

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [30]:
array1 = np.array([1, 2])
array2 = np.array([4, 5])

print(array1 > array2)
print(array1 >= array2)
print(array1 < array2)
print(array1 <= array2)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [38]:
#1 va 2 - hatolik beradi, chunki array hato tuzilgan,  [] ichida bolishi kerak, bunday bolgan taqdirdayam hato beradi, chunki sonni nolga bolib bolmaydi
#3 - avval massivni malumot turini butun sonlarga, keyin haqiqiy sonlarga ozgartiradi


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [48]:
arr18_1 = np.random.randint(18, size=(1, 18))
arr18_2 = np.random.randint(18, size=(1, 18))
print(arr18_1)
print(arr18_2)

bools = np.in1d(arr18_1, arr18_2)
np.unique(arr18_1[0][bools])

[[ 4  6 14 12  2  9  3  1  3  5  4 13  2 15 16  8  7  7]]
[[ 3 10 15  2  0  6  9 13  0  9  9 10  7  0  8 13  5  2]]


array([ 2,  3,  5,  6,  7,  8,  9, 13, 15])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [65]:
#1 - usul

arr19 = np.random.randn(4, 4)
print(arr19)
bools = arr19 >= 0
kasr, butun = np.modf(arr19[bools])
butun

[[ 0.92057618 -0.35448952  0.53962098  0.32164705]
 [ 0.80051639 -0.96745564  1.41095898 -0.50950703]
 [ 0.33030116 -0.08796565 -1.74304706  0.64067133]
 [ 1.00157467  0.7046214  -2.04361848  0.05691851]]


array([0., 0., 0., 0., 1., 0., 0., 1., 0., 0.])

In [66]:
#2 - usul

arr19 = np.random.randn(4, 4)
print(arr19)
bools = arr19 >= 0
butun = np.floor(arr19[bools])
butun

[[-0.92828771 -0.64264079 -1.35816952 -0.55549669]
 [-2.30471314 -0.95803024 -1.03016372 -0.75855741]
 [ 1.97281536  0.93515805  0.45486395 -0.52363569]
 [-0.00433278 -0.2947197   2.19946602  0.48299001]]


array([1., 0., 0., 2., 0.])

In [63]:
#3 - usul

arr19 = np.random.randn(4, 4)
print(arr19)
bools = arr19 >= 0
butun = arr19[bools].astype(int)
butun

[[ 0.96681661  1.17184525  0.20869492  1.43837319]
 [ 0.93642765 -0.52278986  0.63109313 -0.77607379]
 [-0.5479622  -0.67672432  0.60011669 -1.94154084]
 [ 0.2057752  -0.58537933  0.09785256 -0.45195028]]


array([0, 1, 0, 1, 0, 0, 0, 0, 0])

In [64]:
#4 - usul

arr19 = np.random.randn(4, 4)
print(arr19)
bools = arr19 >= 0
butun = np.trunc(arr19[bools])
butun

[[ 0.98159451  0.22149363  0.49297913 -1.01610982]
 [ 0.38098956 -0.31626901 -1.12964419  1.18526991]
 [-0.43433687  0.86974688  1.55616428 -1.9465016 ]
 [ 0.90509853  0.6312985  -1.17179596  1.86520492]]


array([0., 0., 0., 0., 1., 0., 1., 0., 0., 1.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [71]:
row_arr = np.arange(0, 3)
arr20 = np.array([row_arr, row_arr, row_arr])
arr20

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [74]:
arr21 = np.random.randint(105, size=(1, 10))[0]
new_sorted = np.sort(arr21)
new_sorted

array([ 2,  8,  8, 10, 15, 16, 46, 51, 57, 78])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [79]:
arr22_1 = np.random.randn(3, 4)
arr22_2 = np.random.randn(3, 4)

print(arr22_1)
print(arr22_2)
np.array_equal(arr22_1, arr22_2)

[[ 1.81348779  0.14270689 -0.42742615 -0.36429523]
 [-2.52467083 -0.57040823  0.51426776 -0.94996846]
 [-0.59494679 -0.79196565  1.01298247 -1.63801577]]
[[ 0.63499971  0.66128128  1.19770666 -0.02666559]
 [-2.21687774 -0.10825282 -0.43360063  0.16292624]
 [-0.00537431  1.85682979 -0.60944956  0.2835117 ]]


False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [82]:
arr23_1 = np.random.randint(23, size=(6, 3))
arr23_2 = np.random.randint(23, size=(3, 4))
print(arr23_1)

print(arr23_2)

np.dot(arr23_1, arr23_2)

[[16  0 11]
 [22 15 15]
 [ 5 11 20]
 [20  5 13]
 [ 8  7 18]
 [16 11  2]]
[[ 3 12 16  1]
 [ 5  0  2  9]
 [17 14  2  7]]


array([[235, 346, 278,  93],
       [396, 474, 412, 262],
       [410, 340, 142, 244],
       [306, 422, 356, 156],
       [365, 348, 178, 197],
       [137, 220, 282, 129]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [88]:
arr24 = np.random.randn(1, 5)[0]
print(arr24)
np.where(arr24 == np.max(arr24), 0, arr24)

[-0.81687646 -1.67078734 -0.35842933  1.43279012 -0.7391197 ]


array([-0.81687646, -1.67078734, -0.35842933,  0.        , -0.7391197 ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [109]:
bugun = np.datetime64('today')
kecha = bugun - 1
print(bugun)
print(kecha)

2024-01-28
2024-01-27


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

TypeError: 'type' object is not subscriptable

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [133]:
# 19 - misol bilan bir xil

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [135]:
k1 = np.random.randn(2, 3)
k2 = np.random.randn(5, 2)
k3 = np.random.randn(6, 4)

print(np.add.reduce(k1))
print(np.add.reduce(k2))
print(np.add.reduce(k3))

[-1.47728873  1.53162827 -0.987182  ]
[2.32314383 2.6116167 ]
[-4.23164443 -1.35194467 -2.6704119   0.97841584]


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [177]:
a = np.array([1, 2, 3, 4, 5])
s = np.array([])

for i in range((a.size - 1)):
  c = np.append(a[i:i+1], [0,0,0])
  s = np.append(s, c)
s = np.append(s, a[-1])

s

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [187]:
a =  np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b = []

for i in range(1, len(a)-2):
  b.append(list(range(i, i + 4)))
b = np.array(b)
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [188]:
last_arr = np.array([3, 7, 9, 10, 4, 21, 13, 14, 7, 1, 3, 21, 14, 13])
l = last_arr.size - np.unique(last_arr).size
l

5

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

3ta massiv tuzing, uzunligi bir birga teng bolgan 1- va 2- massivlarni ihtiyoriy sonlar bilan to'ldiring, 1 va 2 - massiv larni mos elementlari bir biriga bo'linsa (a = [a1, a2, ...], b = [b1, b2, ....], a1 % b1 == 0 or b1 % a1 == 0), 3 - massivni mos indexiga True, aks holda False qiymatini bering. Va natijani chiqaring.

In [199]:
a = np.random.randint(100, size=(1, 10))[0]
b = np.random.randint(6, size=(1, 10))[0]

print(a)
print(b)

c = (a % b == 0) | (b % a == 0)

print(c)

[58 58 49 94 86 98 37 88 29 67]
[0 3 0 1 5 0 2 3 3 3]
[ True False  True  True False  True False False False False]


<ipython-input-199-89478fbcd543>:7: RuntimeWarning: divide by zero encountered in remainder
  c = (a % b == 0) | (b % a == 0)
